MagmaHideout_2F_2R_MapScripts::
	.byte 0

MagmaHideout_2F_2R_EventScript_Grunt15::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_15, MagmaHideout_2F_2R_Text_Grunt15Intro, MagmaHideout_2F_2R_Text_Grunt15Defeat
	msgbox MagmaHideout_2F_2R_Text_Grunt15PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_Grunt6::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_6, MagmaHideout_2F_2R_Text_Grunt6Intro, MagmaHideout_2F_2R_Text_Grunt6Defeat
	msgbox MagmaHideout_2F_2R_Text_Grunt6PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_Grunt7::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_7, MagmaHideout_2F_2R_Text_Grunt7Intro, MagmaHideout_2F_2R_Text_Grunt7Defeat
	msgbox MagmaHideout_2F_2R_Text_Grunt7PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_Grunt8::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_8, MagmaHideout_2F_2R_Text_Grunt8Intro, MagmaHideout_2F_2R_Text_Grunt8Defeat
	msgbox MagmaHideout_2F_2R_Text_Grunt8PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_Text_Grunt15Intro:
	.string "Hey. Me again. Do you happen to know\n"
	.string "VYRAL’s training routine?\p"
	.string "I bet it’s really intense. Do you\n"
	.string "think she could bench press me.$"

MagmaHideout_2F_2R_Text_Grunt15Defeat:
	.string "I lost because I was distracted\n"
	.string "thinking about VYRAL…$"

MagmaHideout_2F_2R_Text_Grunt15PostBattle:
	.string "All this digging was hard work but\n"
	.string "I bet Vryal could have had it done\l"
	.string "in minutes. I could have sat\p"
	.string "and watched instead of being\n"
	.string "yelled at by our glorious leader.$"

MagmaHideout_2F_2R_Text_Grunt6Intro:
	.string "I can’t stand all this dragon\n"
	.string "grandstanding. Maybe buying a\l"
	.string "lucrative timeshare and settling\l"
	.string "down is for the best.$"

MagmaHideout_2F_2R_Text_Grunt6Defeat:
	.string "HATZOOME seems like a much nicer\n"
	.string "gal than our glorious leader...$"

MagmaHideout_2F_2R_Text_Grunt6PostBattle:
	.string "Don’t you get lonely for the sea\n"
	.string "being in a place like this?$"

MagmaHideout_2F_2R_Text_Grunt7Intro:
	.string "You can hear tremors here sometimes.\p"
	.string "Somebody must have had a real\n"
	.string "nasty curry!$"

MagmaHideout_2F_2R_Text_Grunt7Defeat:
	.string "Flatulence jokes are funny.$"

MagmaHideout_2F_2R_Text_Grunt7PostBattle:
	.string "to be fair you have to have a very\n"
	.string "high IQ in order to understand\l"
	.string "toilet humour…\p"
	.string "I wouldn’t expect a human to get it.$"

MagmaHideout_2F_2R_Text_Grunt8Intro:
	.string "One of our guys was freaking out that\n"
	.string "he lost his FIRE EMBLEM…\p"
	.string "Wait a minute!\n"
	.string "Was it you who found it?$"

MagmaHideout_2F_2R_Text_Grunt8Defeat:
	.string "Was it Fates? Or Three Houses?$"

MagmaHideout_2F_2R_Text_Grunt8PostBattle:
	.string "Our glorious leader is kind of like\n"
	.string "Edelgard, if Edelgard was a dangerous\l"
	.string "lunatic and not a misguided…\p"
	.string "Oh sorry, we don’t need another 5\n"
	.string "years of Three Houses discourse for\l"
	.string "some reason.$"

