SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "I'll show you the sublime techniques\n"
	.string "I learned from our LEADER JUAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Please forgive me, JUAN…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Watch what happens if you crack all\n"
	.string "the floor tiles.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "I am here to win, this isn't just a\n"
	.string "game to me...$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "I've left behind my family, my friends\n"
	.string "- everything...\p"
	.string "The only thing for me is this -\n"
	.string "the battlefield...$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "I lost... can even go back to my wife\n"
	.string "and kids?$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Vier: Its all 4!!!!!! AHAHHAHAHHA\n"
	.string "Pengwynn: Shut up!$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Vier: We lost FOUReal FOURreal\n"
	.string "Pengwynn: Please never talk again...$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "Vier: Fou-\n"
	.string "Pengwynn: Im seriously going to tape\p"
	.string "your mouth!$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "I should teach you how harsh battles\n"
	.string "can be.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh.\n"
	.string "You're strong.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "I'll tell you something good.\p"
	.string "If you want to reach JUAN, you\n"
	.string "need to walk on each floor tile once.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "They're finally here performing\n"
	.string "for you, if you know the words\l"
	.string "you can join in too.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "He may move slow, he can't jump high...$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "But this Kong's one hell of a guy!$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Hi hi, the greatest Sunflower Expert\n"
	.string "Kohaku is here! Ready to taste my\p"
	.string "sunflower lasers?$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "Aw... at least they were pretty, right?$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "When I asked Shiki-sama if he was\n"
	.string "available, he ran away so I guess\l"
	.string "I will have to wait...$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Is that Reya?! I need to say something\n"
	.string "cool. Himabigfan$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Thanks for the battle!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "You think I can get your autograph?$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "A trustworthy guy just sold me\n"
	.string "amazing Pokemon! Wait, you CAUGHT yours?\p"
	.string "What are you, poor?$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "I saw it! You cheated! I saw you use\n"
	.string "rare candies!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Don't ever talk to me or my Arbok again!$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "I can battle with really rare POKéMON\n"
	.string "if you'd like.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Oh, there now! Did you have a good look\n"
	.string "at my POKéMON?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "I came to this GYM because JUAN\n"
	.string "praised me for my darling POKéMON.\p"
	.string "Oh, if only I'd met JUAN years ago\n"
	.string "when I was younger…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Doesn't playing this game make you\n"
	.string "nosetalgic?$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "I guess that me losing was a nose\n"
	.string "brainer!$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "I guess that me losing was a nose\n"
	.string "brainer!$"

